apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: seektable
  name: seektable
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5000
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: seektable
status:
  loadBalancer: {}
